### PR TITLE
Prevent console window on mac and windows

### LINKED ISSUE #16: Prevent console window on macOS and Windows
https://pyinstaller.org/en/stable/usage.html?highlight=windowed#cmdoption-w

### PR DESCRIPTION
**Pull request by ccntrq**
Resolves: #16

### CODE REVIEW

**Comment by dasJake** [comment]
unfortunately it doesn't work. Even after granting execution privileges execution of *.app file is prevented with error
```The application "game.app" can't be opened```


With execution privileges the `game` file can be run but still with the additional console window

**Comment by dasJake** [comment]
2 problems:

1. If I build the the package locally with pyinstaller I can run game.app. If I download the artifact from github I can't run it.
2. If I run the locally built game.app the game crashes before switching to game over view.

**Comment by ccntrq** [comment]
Maybe the executable bit need to be set on the executable inside of the app folder. Let's compare the local build to the cloud one together

**Comment by ccntrq** [comment]
Works fine now.

**Pull request merged**
