### PR TITLE
Prevent flicker on instruction/gameover screen

### LINKED ISSUE #11: Prevent screen flicker on instruction and game over screen
On some devices (modern mac, windows) the instruction and game over screen are flickering. This should be fixed.

Maybe enabling VSync will remedy this problem (Suggested by reddit user in https://www.reddit.com/r/pythonarcade/comments/10wr5yn/screen_flickering_on_macbooks_with_m1m2_chips/)

### PR DESCRIPTION
**Pull request by ccntrq**
Redraw game state for transparency effect instead of drawing over old state

Resolves #11 

Activating vsync didn't help with this problem. We might still want to activate it for smoother drawing. Not in scope of this PR though.

### CODE REVIEW

**Comment by ccntrq** [comment]
@dasJake  Please check if flicker is gone on macOS now.

https://github.com/ccntrq/delirious-dentist/actions/runs/4145591017

**Comment by dasJake** [comment]
works for instruction screen. awesome!

for score board however there are some issues as follows

**Comment by dasJake** [comment]
```jakobflock@Jakobs-MacBook-Air delirious-dentist % python3 game.py 
2023-02-10 17:01:06.417 Python[11209:582269] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/p7/0779f_l95_sbrt7fcth79rq40000gn/T/org.python.python.savedState
Exception in thread Thread-1 (_thread_run):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyglet/media/mediathreads.py", line 76, in _thread_run
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyglet/media/mediathreads.py", line 155, in run
    filled = player.refill_buffer()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyglet/media/drivers/openal/adaptation.py", line 273, in refill_buffer
    self._refill(write_size)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyglet/media/drivers/openal/adaptation.py", line 292, in _refill
    self._queue_audio_data(audio_data, length)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyglet/media/drivers/openal/adaptation.py", line 321, in _queue_audio_data
    buf = self.alsource.get_buffer()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyglet/media/drivers/openal/interface.py", line 271, in get_buffer
    return self.buffer_pool.get_buffer()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyglet/media/drivers/openal/interface.py", line 504, in get_buffer
    return self.get_buffers(1)[0]
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyglet/media/drivers/openal/interface.py", line 516, in get_buffers
    b = self._create_buffer()
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyglet/media/drivers/openal/interface.py", line 534, in _create_buffer
    self._check_error('Error allocating buffer.')
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyglet/media/drivers/openal/interface.py", line 72, in _check_error
    raise OpenALException(message=message,
pyglet.media.drivers.openal.interface.OpenALException: OpenAL Exception [40963: b'Invalid Value']: Error allocating buffer.
Error playing sound. OpenAL Exception [40963: b'Invalid Value']: Error allocating buffer.
```

**Comment by dasJake** [comment]
it seems to keep updating the contents of the score board every second. you can watch the time count up. also it marks all scores as current score (yellow).

**Comment by ccntrq** [comment]
Fixed the scoreboard issue. Should be working now

https://github.com/ccntrq/delirious-dentist/actions/runs/4146465375

**Pull request merged**
